"""
Django settings for django_fc project.

Generated by 'django-admin startproject' using Django 3.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/3.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.1/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '+k@0pqta!6&u9x7k!z8jl3(hafn^cj(o^__egx4515fp^6jhng'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

# Application definition

# Baton setting
BATON = {
    'SITE_HEADER': "BackOffice",
    'SITE_TITLE': "BackOffice",
    'INDEX_TITLE': "BackOffice",
    'SUPPORT_HREF': 'https://google.co.kr',  # 링크
    'COPYRIGHT': 'copyright © 2021 Django_Project',
    'POWERED_BY': '<a href="https://google.co.kr">Django</a>',
    'MENU_TITLE': 'Django_Study',
    'MENU': (
        {'type': 'title', 'label': 'main', 'apps': ('user', 'order', 'product')},
        {
            'type': 'app',
            'name': 'user',
            'label': '사용자',
            'icon': 'fa fa-lock',
            'models': (
                {
                    'name': 'user',
                    'label': '사용자'
                },
            )
        },

        {'type': 'free', 'label': '주문', 'default_open': True, 'children': [
            {'type': 'model', 'label': '주문', 'name': 'order', 'app': 'order'},
            {'type': 'free', 'label': '주문 날짜 뷰', 'url': '/admin/order/order/date_view/'},
            ]
         },
            {
                'type': 'app',
                'name': 'product',
                'label': '상품',
                'models': (
                    {
                        'name': 'product',
                        'label': '상품'
                    },
                )
            },
            {'type': 'free', 'label': '매뉴얼', 'url': '/admin/manual'},
    ),
}
INSTALLED_APPS = [
    'baton',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',
    'rest_framework',
    'user.apps.UserConfig',
    'product.apps.ProductConfig',
    'order.apps.OrderConfig',

    'baton.autodiscover'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'django_fc.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')]  # 설정해야 main dir 에 있는 templates 연결 가능
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'django_fc.wsgi.application'

# Database
# https://docs.djangoproject.com/en/3.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# Password validation
# https://docs.djangoproject.com/en/3.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/3.1/topics/i18n/

LANGUAGE_CODE = 'ko-kr'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.1/howto/static-files/

STATIC_URL = '/static/'
